### ISSUE TITLE
No need to wait after Wire.requestFrom() and no Wire.beginTransmission() or endTransmission() should be used with Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [jarzebski/Arduino-MS5611#2]
See: https://github.com/jarzebski/Arduino-INA219/issues/1

The file "MS5611.cpp" has a number of issues.
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1, 2, 3 and 5.

**Comment by jarzebski** [comment]
will be fixed in 1.1.0 release
