### ISSUE TITLE
Altitude obviously wrong

### ISSUE THREAD

**Issue by nesdnuma** [jarzebski/Arduino-MS5611#4]
Hello,

I am trying to use your library on an Arduino UNO R2. The temperatures provided by the _MS5611_simple_ example seem to be correct but not the absolute altitudes (I have 26m instead of 57 above sea level).

**Comment by impala454** [comment]
Weather conditions affect the pressure readings so you're not going to get an exact altitude calculation unless you can feed in a nearby sea level reference pressure.  The `absoluteAltitude = ms5611.getAltitude(realPressure);` in the example is a bit of a misnomer.  If this is for a moving device, you could always call the `getSeaLevel()` function to get that sea level reference pressure, given the known starting altitude.  If it's a fixed base device well then you can just look up the altitude.

**Comment by nesdnuma** [comment]
OK, thanks!
