### ISSUE TITLE
Library hangs if temperature< 20

### ISSUE THREAD

**Issue by RC-Thoughts** [jarzebski/Arduino-MS5611#7]
Library hangs whole sketch when temperature comes down below 20. 

Fix: 

In MS5611.cpp change line 184 from
`TEMP2 = (dT * dT) / (2 << 30);`
to
`TEMP2 = (dT * dT) / pow(2, 31);`

And all is well again.

**Comment by heliflieger** [comment]
Please Update your Lib.

**Comment by jarzebski** [comment]
will be fixed in 1.1.0 release
